### ISSUE TITLE
reauth each request

### ISSUE THREAD

**Issue by jbodah** [jbodah/spotifuby#28]
auth is expiring, need to reauthenticate with each request

**Comment by thebmo** [comment]
should we make this smart and only reauth if past a time threshold?

**Comment by jbodah** [comment]
> should we make this smart and only reauth if past a time threshold?

I don't think it's worth it. I think simply calling `RSpotify.authenticate` before everything in `Spotify::Web` would be fine

**Comment by jbodah** [comment]
4bb9e6efafcd143f31f7dd729eb50e49313f79b0
